name: create-issue-branch (chatops)
on:
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [closed]
permissions:
  contents: write
  issues: write
  pull-requests: write
jobs:
  run:
    if: ${{ github.event.issue.pull_request == null }}
    runs-on: ubuntu-latest
    steps:
      - uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
