on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  run_ci_checks:
    uses: ./.github/workflows/push-main.yaml
    secrets: inherit

  build_and_release:
    needs: run_ci_checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Release
        run: |
          gh release create ${{github.ref_name}} --generate-notes
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
